# Note: The Gemini model key (currently 'gemini-2.0-flash-thinking-exp-01-21') 
# should match the GEMINI_REASONING_MODEL environment variable defined in .env.local
textmodels:
  gemini-2.0-flash-thinking-exp-01-21:
    max_output_tokens: 12000
    reasoning_effort: 3
    top_k: 40
    context_management: dynamic
  claude-3.5-sonnet-20241022:
    max_output_tokens: 8000
    temperature: 0.2
    stop_sequences:
      - "\\n\\nHuman:"
      - "\\n\\nAssistant:"
